# Database Configuration
spring.datasource.url=jdbc:sqlite:../farm_manager.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Server Config
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.farmmanager=DEBUG
